---
- name: learning to register
  hosts: planet-express
  gather_facts: yes
  
  tasks:
          - name: reach out and get url
            get_url:
                    url: https://www.random.org/integers/?num=1&min=0&max=1&col=1&base=10&format=plain&rnd=new
                    dest: ~/rand.txt
                    force: yes

          - name: read a file and save the results
            command: cat ~/rand.txt
            register: readfile

          - name: You won
            debug:
                    msg: "congrats you win! :)"
            when: readfile.stdout == "1"

          - name: You lost
            debug:
                    msg: "Loooooooooser"
            when: readfile.stdout == "0"
            
          - name: show the contents of the file
            debug:
                    var: readfile.stdout
